# Generated by Django 4.2 on 2023-04-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alpha", models.CharField(max_length=50, verbose_name="Сущности")),
                (
                    "current_value_c1",
                    models.IntegerField(default=0, verbose_name="Цикл_1"),
                ),
                (
                    "current_value_c2",
                    models.IntegerField(default=0, verbose_name="Цикл_2"),
                ),
                (
                    "current_value_c3",
                    models.IntegerField(default=0, verbose_name="Цикл_3"),
                ),
                (
                    "current_value_c4",
                    models.IntegerField(default=0, verbose_name="Цикл_4"),
                ),
                (
                    "current_value_c5",
                    models.IntegerField(default=0, verbose_name="Цикл_5"),
                ),
                (
                    "current_value_c6",
                    models.IntegerField(default=0, verbose_name="Цикл_6"),
                ),
                (
                    "current_value_c7",
                    models.IntegerField(default=0, verbose_name="Цикл_7"),
                ),
                (
                    "current_value_c8",
                    models.IntegerField(default=0, verbose_name="Цикл_8"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
