# Generated by Django 4.2 on 2023-04-27 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_post_options_remove_post_alpha_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.CreateModel(
            name="Est",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle", models.IntegerField(default=1, verbose_name="Цикл")),
                (
                    "zainteresovannye_storony",
                    models.IntegerField(
                        default=0, verbose_name="Заинтересованные стороны"
                    ),
                ),
                (
                    "vosmojnost",
                    models.IntegerField(default=0, verbose_name="Возможность"),
                ),
                (
                    "trebovaniya",
                    models.IntegerField(default=0, verbose_name="Требования"),
                ),
                (
                    "programmnaya_sistema",
                    models.IntegerField(default=0, verbose_name="Программная система"),
                ),
                ("rabota", models.IntegerField(default=0, verbose_name="Работа")),
                ("komanda", models.IntegerField(default=0, verbose_name="Команда")),
                (
                    "tehnologiya_raboty",
                    models.IntegerField(default=0, verbose_name="Технология работы"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные_",
                "verbose_name_plural": "Данные_",
            },
        ),
    ]
